services:
    khp-back:
        container_name: khp-back
        build:
            context: ./
            dockerfile: ./docker/php/Dockerfile.local
        ports:
            - ${APP_PORT:-8000}:8000
            - ${VITE_PORT:-5173}:${VITE_PORT:-5173}
        volumes:
            - ./:/var/www/html
            - ./vendor/:/var/www/html/vendor
        networks:
            - khp-back
        depends_on:
            - khp-postgres
            - khp-redis
            - khp-mailpit

    khp-postgres:
        image: "postgres:15"
        container_name: khp-postgres
        ports:
            - "${FORWARD_DB_PORT:-5432}:5432"
        environment:
            POSTGRES_USER: "${DB_USERNAME:-khp}"
            POSTGRES_PASSWORD: "${DB_PASSWORD:-password}"
            POSTGRES_DB: "${DB_DATABASE:-khp_database}"
        volumes:
            - "khp-postgres:/var/lib/postgresql/data"
        networks:
            - khp-back
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "${DB_USERNAME:-khp}"]
            retries: 3
            timeout: 5s

    khp-redis:
        image: redis:alpine
        container_name: khp-redis
        ports:
            - ${FORWARD_REDIS_PORT:-6379}:6379
        volumes:
            - "khp-redis:/data"
        networks:
            - khp-back
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s

    khp-mailpit:
        container_name: khp-mailpit
        image: axllent/mailpit
        volumes:
            - khp-mailpit:/data
        networks:
            - khp-back
        ports:
            - 8025:8025
            - 1025:1025
        environment:
            MP_MAX_MESSAGES: 5000
            MP_DATA_FILE: /data/mailpit.db
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1
networks:
    khp-back:
        driver: bridge

volumes:
    khp-postgres:
        driver: local
    khp-redis:
        driver: local
    khp-mailpit:
        driver: local
