<?php

namespace Database\Factories;

use App\Enums\MeasurementUnit;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Ingredient>
 */
class IngredientFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $ingredients = [
            'Tomate',
            'Oignon',
            'Ail',
            'Carotte',
            'Pomme de terre',
            'Courgette',
            'Aubergine',
            'Poivron rouge',
            'Poivron vert',
            'Brocoli',
            'Chou-fleur',
            'Épinards',
            'Salade',
            'Concombre',
            'Radis',
            'Betterave',
            'Navet',
            'Poireau',
            'Céleri',
            'Persil',
            'Basilic',
            'Coriandre',
            'Thym',
            'Romarin',
            'Oregano',
            'Menthe',
            'Ciboulette',
            'Aneth',
            'Sauge',
            'Laurier',
            'Paprika',
            'Cumin',
            'Curry',
            'Gingembre',
            'Cannelle',
            'Muscade',
            'Clou de girofle',
            'Cardamome',
            'Anis',
            'Fenouil',
            'Riz',
            'Pâtes',
            'Quinoa',
            'Boulgour',
            'Avoine',
            'Orge',
            'Semoule',
            'Farine de blé',
            'Farine de riz',
            'Fecule de pomme de terre',
            'Levure',
            'Huile d\'olive',
            'Huile de tournesol',
            'Beurre',
            'Margarine',
            'Crème fraîche',
            'Lait',
            'Yaourt',
            'Fromage blanc',
            'Gruyère',
            'Parmesan',
            'Mozzarella',
            'Chèvre',
            'Roquefort',
            'Camembert',
            'Œufs',
            'Poulet',
            'Bœuf',
            'Porc',
            'Agneau',
            'Saumon',
            'Thon',
            'Crevettes',
            'Moules',
            'Cabillaud',
            'Sardines',
            'Haricots verts',
            'Petits pois',
            'Haricots rouges',
            'Lentilles',
            'Pois chiches',
            'Amandes',
            'Noix',
            'Noisettes',
            'Pignons',
            'Graines de tournesol',
            'Pomme',
            'Poire',
            'Banane',
            'Orange',
            'Citron',
            'Pamplemousse',
            'Kiwi',
            'Fraise',
            'Framboise',
            'Myrtille',
            'Cerise',
            'Abricot',
            'Pêche',
            'Prune',
            'Raisin',
            'Melon',
            'Pastèque',
            'Ananas',
            'Mangue',
            'Avocat',
            'Olives',
            'Sucre',
            'Miel',
            'Sirop d\'érable',
            'Chocolat noir',
            'Chocolat au lait',
            'Cacao en poudre',
            'Vanille',
            'Café',
            'Thé',
            'Vinaigre balsamique',
            'Vinaigre de vin',
            'Moutarde',
            'Ketchup',
            'Mayonnaise',
            'Sauce soja',
        ];

        return [
            'name' => $this->faker->randomElement($ingredients).' '.$this->faker->numberBetween(1, 999),
            'unit' => $this->faker->randomElement(MeasurementUnit::values()),
            'base_quantity' => $this->faker->numberBetween(1, 1000),
            'barcode' => $this->faker->unique()->ean13(),
        ];
    }
}
