name: Laravel CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  laravel-ci:
    name: Laravel CI Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          extensions: mbstring, pdo, tokenizer, xml, ctype, fileinfo
          coverage: xdebug # Activation de Xdebug pour la couverture de code
          tools: composer:v2

      - name: Restore Composer cache
        uses: actions/cache@v3
        with:
          path: ./vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Setup environment
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Run Larastan (PHPStan)
        run: ./vendor/bin/phpstan analyse --memory-limit=4G

      - name: Run PHPUnit tests
        run: XDEBUG_MODE=coverage ./vendor/bin/phpunit
